# Environments
DEVICE: 0

# Object Detector
DET_MODEL_TYPE: "yolo"
DET_MODEL_PATH: './weights/yolov5s.pt'
IMG_SIZE: 640
HALF: false

# Object Tracker
TRACK_USE_ENCODER: false
TRACK_MODEL_TYPE: "deepocsort"
TRACK_MODEL_PATH: "./weights/osnet_x0_25_market1501.pt"
TRACK_HALF: false

# Logger
LOG_LEVEL: 'INFO'
CONSOLE_LOG: true
LOGGER_NAME: "OBJ"
FILE_LOG: true
LOG_FILE_DIR: './log/'
LOG_FILE_COUNTER: 10
LOG_FILE_ROTATE_TIME: "D"
LOG_FILE_ROTATE_INTERVAL: 1

