# Environments
DEVICE: 0

# Object Detector
DET_MODEL_TYPE: "yolo"
DET_MODEL_PATH: './weights/qtum_half1_x6.pt'
IMG_SIZE: 1280
HALF: false
OBJ_CLASSES: [0, 1, 2, 3]
CONF_THRES: 0.5
NMS_IOU: 0.65

# Logger
LOG_LEVEL: 'debug'
CONSOLE_LOG: true
LOGGER_NAME: "annotation"
FILE_LOG: true
LOG_FILE_DIR: './log/'
LOG_FILE_COUNTER: 10
LOG_FILE_ROTATE_TIME: "D"
LOG_FILE_ROTATE_INTERVAL: 1

