# Environments
DEVICE: 0

# Object Detector
DET_MODEL_TYPE: "yolo"
DET_MODEL_PATH: './weights/crowdhuman_yolov5m.pt'
IMG_SIZE: 640
HALF: false
OBJ_CLASSES: None
CONF_THRES: 0.3
NMS_IOU: 0.65

# Logger
LOG_LEVEL: 'debug'
CONSOLE_LOG: true
LOGGER_NAME: "MOSAIC"
FILE_LOG: true
LOG_FILE_DIR: './log/'
LOG_FILE_COUNTER: 10
LOG_FILE_ROTATE_TIME: "D"
LOG_FILE_ROTATE_INTERVAL: 1

